### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by eldelacajita** [soyersoyer/cameractrls#8]
Creating this as a separate issue, coming from the conversation at #7.

Here are some first attempts, in two different directions and with slightly different styles.

## Physical camera and sliders representing "settings"
I have used simple shapes, no reflections, no gradients, but some drop shadows.

![Captura desde 2022-12-05 13-44-07](https://user-images.githubusercontent.com/2880679/205640888-1ada0d0b-ef07-464b-8bf6-aad3e6f82177.png)

This variation ended up looking more like an action camera, but I'm including it anyway.

![Captura desde 2022-12-05 13-37-22](https://user-images.githubusercontent.com/2880679/205640922-e1dd69bb-68b1-457d-a82b-d3afda1806b0.png)

## A different approach, combining the settings icon with a camera
Here I tried a slightly more detailed style, with some gradients and reflections.

![Captura desde 2022-12-05 13-37-30](https://user-images.githubusercontent.com/2880679/205640907-6c3468aa-7f86-4edf-8dc8-e93d7bb8260b.png)

What do you think? Feel free to tell me you want something entirely different, I'm having fun exploring anyway :smile:

**Comment by eldelacajita** [comment]
Here I come with some more variations: 

## Separating camera and settings 
A combination of a more webcam-like camera and a settings panel that appears under it. 

![Captura desde 2022-12-05 16-24-41](https://user-images.githubusercontent.com/2880679/205675804-5d878c5c-cb71-4d9c-b28d-93a609a7b20b.png)

The same, but moving the red dot and adding a microphone hole to make it somehow symmetric. Also, slightly adjusting the width of the settings panel to make it look more balanced (in the version above, it looks wider than the camera because it's brighter).

![Captura desde 2022-12-05 16-32-01](https://user-images.githubusercontent.com/2880679/205677068-681f61fd-52ef-4fa1-bf2d-056b647c9490.png)

**Comment by eldelacajita** [comment]
Once we settle on one of these concepts, I can polish it more and make the symbolic icon, too.

**Comment by soyersoyer** [comment]
Wow, these are cool! I like the 05c best.
Could you add 2 or 3 more mic hole for future safety?
I think the lens could be a bit bigger, like sony compacts (eg a6000, zv1) where the lens is almost as tall as the body.

**Comment by eldelacajita** [comment]
Those are great references, thank you!

I'll try to find a balance between keeping it simple and generic, but also evocative of those devices.

**Comment by eldelacajita** [comment]
Here's another variant: 

![Captura desde 2022-12-08 17-38-28](https://user-images.githubusercontent.com/2880679/206510889-fbc4badc-888c-4fa1-affb-5e4765f08ec6.png)

And the same with a more detailed style: 

![Captura desde 2022-12-08 17-41-48](https://user-images.githubusercontent.com/2880679/206511571-d884f476-8a1a-4e78-97e8-06bc129386e9.png)

I'm not sure if I like it better than the 5c, though. To make the lens bigger and still have space for two mic holes each side, I had to make the camera less tall and give more proportional space to the settings panel. Also, it becomes less abstract, and we could end up sliding into a rabbit hole trying to imitate real life cameras.

Anyway, let me know what you think!

**Comment by soyersoyer** [comment]
I like the 06b. It feels more modern to me. Maybe because of the camera's proportions. Could you make one more version of the 06b without the double mic, and another version of the 05c with detailed lens?

**Comment by eldelacajita** [comment]
Here they are. I also noticed that I was making the 5c variant too tall for the template, so after adjusting that too, they both ended being quite similar except for the size of the lens: 

![imagen](https://user-images.githubusercontent.com/2880679/206874078-1f2dfc33-709f-4949-9434-29de3b4ce27d.png)

![imagen](https://user-images.githubusercontent.com/2880679/206873988-6f565c7e-59f9-4461-9f4a-6b1fcccb4bde.png)

I think any of these last variants (6b, 6b-2, 5c-2) can work, so we can choose the one you like the most, with some final touches if needed.

**Comment by eldelacajita** [comment]
Hi, @soyersoyer! How is everything going? Let me know if you want me to continue with this and export the final icon. Which one do you prefer?

**Comment by soyersoyer** [comment]
Sorry for the late reply.
Could we have one more version?
My idea is to
color the lens reflection from white to red(ish),
highlight the aperture blades (5-6), to notice this is a settings app.
so we can remove the light part with the slider, the red light, the microphone, and possibly the camera body as well.
What do you think?

**Comment by eldelacajita** [comment]
Something like this?

![cameractrls-07b](https://user-images.githubusercontent.com/2880679/222980762-107bccb4-e475-45f0-a174-9f0cd16f04fd.png)

**Comment by soyersoyer** [comment]
Yes, it's very good! If you export it, I can change the icon to it.

**Comment by eldelacajita** [comment]
Hi! Sorry for the delay. Here it is:

Final version with included symbolic icon:

![cameractrls-07b-final](https://github.com/soyersoyer/cameractrls/assets/2880679/689a5c43-6c2a-45d1-b425-1841af62fb45)


Optimized version, ready to use (exported from the Icon preview app)

![cameractrls-07b-export](https://github.com/soyersoyer/cameractrls/assets/2880679/8d2c2a5d-d08d-48ad-8174-2a80b508b404)

**Comment by nekohayo** [comment]
There's one issue with the closed aperture lens being used as a standalone icon without the "camera body" though, if you intend the details / blades to be visible, they don't really seem to be; not enough contrast between the dark gray of the blades and the pure black of the iris and space between blades, I think. This will be particularly hard to interpret visually on a light background (when gnome shell eventually gets a light theme, maybe) or on uncalibrated monitors.

In reality, unless the scene is completely dark, aperture blades are usually much brighter, and the division lines between the blades have shades and highlights that depend on the angle the light is at, they're not pure black everywhere (you could probably use a bunch of gradients for this). Blades themselves will tend to have a gradient instead of being totally flat, but maybe that's an aesthetic choice here.

See the photos of aperture blades there for reference:

* https://en.wikipedia.org/wiki/Aperture#/media/File:Canon_EF-M_32mm_F1.4_STM_lens-aperture_blades_PNr%C2%B00803.jpg
* https://photographylife.com/wp-content/uploads/2022/10/ApertureBlades.jpg
* https://petapixel.com/assets/uploads/2022/09/aperture-in-photography-featured-image.jpg (there are also many other different aperture blade photos in [that article](https://petapixel.com/what-is-aperture-in-photography/) that show the looks depending on the ambient lighting)

**Comment by nekohayo** [comment]
That said, this is less of an issue if the lens is embedded in the camera "body" with its sliders, because then it's not "just a circle like the gazillion other camera apps that are just a lens"; in that case it can make sense for the aperture blades to be a bit less prominent.

I do think the versions embedded in a camera body with sliders are more unique, recognizeable, and "understandable in what the app's function is" than just the lens.

**Comment by nekohayo** [comment]
...and one more idea: if you want to give the icon a truly distinctive shape/silouhette (instead of being yet another circle / rectangle), you could grab one of those "webcam sitting atop a settings panel" variants above and trim the width of the settings area (the white part, which has thick margins on the left and right anyway) so that it's not as wide as the camera's gray body area, and this would give it a "T" shape that is very much like the shape of actual webcams with their foot. Essentially, you'd be hiding the settings sliders into a white foot ;)

**Comment by eldelacajita** [comment]
> In reality, unless the scene is completely dark, aperture blades are usually much brighter, and the division lines between the blades have shades and highlights that depend on the angle the light is at, they're not pure black everywhere (you could probably use a bunch of gradients for this). Blades themselves will tend to have a gradient instead of being totally flat, but maybe that's an aesthetic choice here.

Yes, it's all very simplified by choice. We are not aiming at a realistic/skeuomorphic design.

That said, you have a point here:

> if you intend the details / blades to be visible, they don't really seem to be

I could try to improve that, although I'd probably have to change several colors to make this work better within the restricted GNOME palette.

**Comment by eldelacajita** [comment]
> I do think the versions embedded in a camera body with sliders are more unique, recognizeable, and "understandable in what the app's function is" than just the lens.

I agree. But regarding that, and your other suggestion, I'll wait to see if @soyersoyer wants to go that way.

**Comment by eldelacajita** [comment]
> I could try to improve that, although I'd probably have to change several colors to make this work better within the restricted GNOME palette.

![test](https://github.com/soyersoyer/cameractrls/assets/2880679/37169394-a4b9-4259-93c4-ed5dcc4773a2)

I tried making the blade lines a bit thicker, the blades a bit lighter, and the outer ring darker. I'm not very convinced of this. One challenge is to keep enough contrast between the blades and the red reflection (I want a dark background for it to stand out). Another challenge is to keep this looking more or less right without trying to go realistic.

**Comment by eldelacajita** [comment]
Sure, here it is:

![cameractrls-07b-export](https://github.com/soyersoyer/cameractrls/assets/2880679/180c7353-2ba5-4bd1-a55f-40630e623ead)

**Comment by soyersoyer** [comment]
I like the 7a better. It looks great with the red flare in the apps.
I think it's better than 6b, because 6b can be the logo of any camera control app, but this is more unique even if there are apps with lens logo.
Thanks. I'll add it to the project soon.
And sorry for the slow replies.

**Comment by eldelacajita** [comment]
Glad to see the new icon among my apps!

This issue can be closed, I suppose.

**Comment by soyersoyer** [comment]
I also added you to the About popup. Thanks for everything.
